name: Tester

on: [pull_request, push]

jobs:
  tester:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Install dependencies
        run: go mod vendor

      - name: Run tests
        run: go test -v ./...
